// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQj7mDubrYfOr7X_rxsNE6QePl4TY0l3g',
    appId: '1:643013739435:web:07e9bf54e37559e45548ee',
    messagingSenderId: '643013739435',
    projectId: 'voltnest-62547',
    authDomain: 'voltnest-62547.firebaseapp.com',
    storageBucket: 'voltnest-62547.firebasestorage.app',
    measurementId: 'G-EX6W5YQDWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg1trK4EmOhwRgvdu4g6YV3Axa-H7AxR8',
    appId: '1:643013739435:android:674743edf9fe4e0c5548ee',
    messagingSenderId: '643013739435',
    projectId: 'voltnest-62547',
    storageBucket: 'voltnest-62547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJhzt8d0LxqsqMmRqYv7T5a0xEehIWVU',
    appId: '1:643013739435:ios:017da4e9760696f05548ee',
    messagingSenderId: '643013739435',
    projectId: 'voltnest-62547',
    storageBucket: 'voltnest-62547.firebasestorage.app',
    iosClientId: '643013739435-i0n29qsegurjkvqr6fopc2pra2a214mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.voltev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKJhzt8d0LxqsqMmRqYv7T5a0xEehIWVU',
    appId: '1:643013739435:ios:017da4e9760696f05548ee',
    messagingSenderId: '643013739435',
    projectId: 'voltnest-62547',
    storageBucket: 'voltnest-62547.firebasestorage.app',
    iosClientId: '643013739435-i0n29qsegurjkvqr6fopc2pra2a214mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.voltev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQj7mDubrYfOr7X_rxsNE6QePl4TY0l3g',
    appId: '1:643013739435:web:e85b2b928dfe2bcb5548ee',
    messagingSenderId: '643013739435',
    projectId: 'voltnest-62547',
    authDomain: 'voltnest-62547.firebaseapp.com',
    storageBucket: 'voltnest-62547.firebasestorage.app',
    measurementId: 'G-4PSVV1EF49',
  );
}
